services:
  web:
    build:
      context: .
      args:
        VERSION: "0.2.0-dev"
        VCS_REF: "${SONIC_SENTRY_VCS_REF:-dev}"
        BUILD_DATE: "${SONIC_SENTRY_BUILD_DATE:-local}"
    image: spacechips/sonic-sentry:dev

  worker:
    build:
      context: .
      args:
        VERSION: "0.2.0-dev"
        VCS_REF: "${SONIC_SENTRY_VCS_REF:-dev}"
        BUILD_DATE: "${SONIC_SENTRY_BUILD_DATE:-local}"
    image: spacechips/sonic-sentry:dev
